Added missing include for `uid_t` type.
This fixes the following compilation error (at least under clang), caused by missing include for `uid_t`.
```
SystemFileChecker.cpp:43:25: error: out-of-line definition of 'isSystemUid' does not match any declaration in 'QDirStat::SystemFileChecker'
bool SystemFileChecker::isSystemUid( uid_t uid )